config/routes.rb
FILENAME_REGEXP = /[\w\.]+/ unless Kernel.const_defined?(:FILENAME_REGEXP)

Rails.application.routes.draw do
  resources :error_template_attributes
  resources :error_templates do
    member do
      put 'attribute', to: 'error_templates#add_attribute'
      delete 'attribute', to: 'error_templates#remove_attribute'
    end
  end
  resources :file_templates do
    collection do
      get 'by_file_type/:file_type_id', as: :by_file_type, action: :by_file_type
    end
  end
  resources :code_harbor_links
  resources :request_for_comments do
    member do
      get :mark_as_solved
      post :create_comment_exercise
      post :set_thank_you_note
    end
  end
  resources :comments
  get '/my_request_for_comments', as: 'my_request_for_comments', to: 'request_for_comments#get_my_comment_requests'
  get '/my_rfc_activity', as: 'my_rfc_activity', to: 'request_for_comments#get_rfcs_with_my_comments'

  delete '/comment_by_id', to: 'comments#destroy_by_id'
  put '/comments', to: 'comments#update'

  resources :subscriptions do
    member do
      get :unsubscribe, to: 'subscriptions#destroy'
    end
  end

  root to: 'application#welcome'

  namespace :admin do
    get 'dashboard', to: 'dashboard#show'
  end

  get '/help', to: 'application#help'

  get 'statistics/', to: 'statistics#show'
  get 'statistics/graphs', to: 'statistics#graphs'
  get 'statistics/graphs/user-activity', to: 'statistics#user_activity'
  get 'statistics/graphs/user-activity-history', to: 'statistics#user_activity_history'
  get 'statistics/graphs/rfc-activity', to: 'statistics#rfc_activity'
  get 'statistics/graphs/rfc-activity-history', to: 'statistics#rfc_activity_history'

  concern :statistics do
    member do
      get :statistics
    end
  end


  resources :consumers

  resources :execution_environments do
    member do
      get :shell
      post 'shell', as: :execute_command, action: :execute_command
      get :statistics
    end

    resources :errors, only: [:create, :index, :show]
    resources :hints
  end

  post '/import_proforma_xml' => 'exercises#import_proforma_xml'

  resources :exercises do
    collection do
      match '', to: 'exercises#batch_update', via: [:patch, :put]
    end

    member do
      post :clone
      get :implement
      get :working_times
      post :intervention
      post :search
      get :statistics
      get :feedback
      get :reload
      post :submit
    end
  end

  resources :exercise_collections do
    member do
      get :statistics
    end
  end

  resources :proxy_exercises do
    member do
      post :clone
      get :reload
      post :submit
    end
  end

  resources :tags do
    member do
      post :clone
      get :reload
      post :submit
    end
  end

  resources :user_exercise_feedbacks do
    member do
      get :reload
      post :submit
    end
  end

  resources :interventions do
    member do
      post :clone
      get :reload
      post :submit
    end
  end

  resources :external_users, only: [:index, :show], concerns: :statistics do
    resources :exercises, concerns: :statistics
    member do
      get :tag_statistics
    end
  end

  namespace :code_ocean do
    resources :files, only: [:create, :destroy]
  end

  resources :file_types

  resources :internal_users do
    member do
      match 'activate', to: 'internal_users#activate', via: [:get, :patch, :put]
      match 'reset_password', to: 'internal_users#reset_password', via: [:get, :patch, :put]
    end
  end

  match '/forgot_password', as: 'forgot_password', to: 'internal_users#forgot_password', via: [:get, :post]

  resources :sessions, only: [:create, :destroy, :new]

  post '/lti/launch', as: 'lti_launch', to: 'sessions#create_through_lti'
  get '/lti/return', as: 'lti_return', to: 'sessions#destroy_through_lti'
  get '/sign_in', as: 'sign_in', to: 'sessions#new'
  delete '/sign_out', as: 'sign_out', to: 'sessions#destroy'

  resources :submissions, only: [:create, :index, :show] do
    member do
      get 'download', as: :download, action: :download
      get 'download/:filename', as: :download_file, constraints: {filename: FILENAME_REGEXP}, action: :download_file
      get 'render/:filename', as: :render, constraints: {filename: FILENAME_REGEXP}, action: :render_file
      get 'run/:filename', as: :run, constraints: {filename: FILENAME_REGEXP}, action: :run
      get :score
      get :statistics
      post :stop
      get 'test/:filename', as: :test, constraints: {filename: FILENAME_REGEXP}, action: :test
    end
  end

  resources :events, only: [:create]

  post "/evaluate", to: 'remote_evaluation#evaluate', via: [:post]

end

app/models/hint.rb
class Hint < ActiveRecord::Base
  belongs_to :execution_environment

  validates :execution_environment_id, presence: true
  validates :locale, presence: true
  validates :message, presence: true
  validates :name, presence: true
  validates :regular_expression, presence: true

  def self.nested_resource?
    true
  end

  def to_s
    name
  end
end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
  include CommonBehavior

  before_action :set_execution_environment
  before_action :set_hint, only: MEMBER_ACTIONS

  def authorize!
    authorize(@hint || @hints)
  end
  private :authorize!

  def create
    @hint = Hint.new(hint_params)
    authorize!
    create_and_respond(object: @hint, path: proc { execution_environment_hint_path(@execution_environment, @hint) })
  end

  def destroy
    destroy_and_respond(object: @hint, path: execution_environment_hints_path(@execution_environment))
  end

  def edit
  end

  def hint_params
    params[:hint].permit(:locale, :message, :name, :regular_expression).merge(execution_environment_id: @execution_environment.id)
  end
  private :hint_params

  def index
    @hints = @execution_environment.hints.order(:name).paginate(page: params[:page])
    authorize!
  end

  def new
    @hint = Hint.new
    authorize!
  end

  def set_execution_environment
    @execution_environment = ExecutionEnvironment.find(params[:execution_environment_id])
  end
  private :set_execution_environment

  def set_hint
    @hint = Hint.find(params[:id])
    authorize!
  end
  private :set_hint

  def show
  end

  def update
    update_and_respond(object: @hint, params: hint_params, path: execution_environment_hint_path(@execution_environment, @hint))
  end
end

app/views/hints/_form.html.slim
= form_for(@hint, url: execution_environment_hints_path(params[:execution_environment_id])) do |f|
  = render('shared/form_errors', object: @hint)
  .form-group
    = f.label(:name)
    = f.text_field(:name, class: 'form-control', required: true)
  .form
    = f.label(:locale)
    = f.select(:locale, I18n.available_locales.map { |locale| [t("locales.#{locale}"), locale] }, {}, class: 'form-control')
  .form-group
    = f.label(:message)
    = f.text_field(:message, class: 'form-control', placeholder: "'$2' has no method '$1'.", required: true)
    .help-block = t('.hints.message')
  .form-group
    = f.label(:regular_expression)
    = f.text_field(:regular_expression, class: 'form-control', placeholder: 'undefined method (\w+) for (\w+)', required: true)
    .help-block = t('.hints.regular_expression')
  .actions = render('shared/submit_button', f: f, object: @hint)

app/views/hints/edit.html.slim
h1 = @hint

= render('form')

app/views/hints/index.html.slim
h1 = Hint.model_name.human(count: 2)

.table-responsive
  table.table
    thead
      tr
        th = t('activerecord.attributes.hint.name')
        th = t('activerecord.attributes.hint.locale')
        th colspan=3 = t('shared.actions')
    tbody
      - @hints.each do |hint|
        tr
          td = hint.name
          td = t("locales.#{hint.locale}")
          td = link_to(t('shared.show'), execution_environment_hint_path(params[:execution_environment_id], hint.id))
          td = link_to(t('shared.edit'), edit_execution_environment_hint_path(params[:execution_environment_id], hint.id))
          td = link_to(t('shared.destroy'), execution_environment_hint_path(params[:execution_environment_id], hint.id), data: {confirm: t('shared.confirm_destroy')}, method: :delete)

= render('shared/pagination', collection: @hints)
p = render('shared/new_button', model: Hint, path: new_execution_environment_hint_path(params[:execution_environment_id]))

app/views/hints/new.html.slim
h1 = t('shared.new_model', model: Hint.model_name.human)

= render('form')

app/views/hints/show.html.slim
h1
  = @hint
  = render('shared/edit_button', object: @hint, path: edit_execution_environment_hint_path(params[:execution_environment_id], @hint.id))

= row(label: 'hint.name', value: @hint.name)
= row(label: 'hint.locale', value: t("locales.#{@hint.locale}"))
= row(label: 'hint.message', value: @hint.message)
= row(label: 'hint.regular_expression', value: code_tag(@hint.regular_expression))