config/routes.rb
FILENAME_REGEXP = /[\w\.]+/ unless Kernel.const_defined?(:FILENAME_REGEXP)

Rails.application.routes.draw do
  resources :error_template_attributes
  resources :error_templates do
    member do
      put 'attribute', to: 'error_templates#add_attribute'
      delete 'attribute', to: 'error_templates#remove_attribute'
    end
  end
  resources :file_templates do
    collection do
      get 'by_file_type/:file_type_id', as: :by_file_type, action: :by_file_type
    end
  end
  resources :code_harbor_links
  resources :request_for_comments do
    member do
      get :mark_as_solved
      post :create_comment_exercise
      post :set_thank_you_note
    end
  end
  resources :comments
  get '/my_request_for_comments', as: 'my_request_for_comments', to: 'request_for_comments#get_my_comment_requests'
  get '/my_rfc_activity', as: 'my_rfc_activity', to: 'request_for_comments#get_rfcs_with_my_comments'

  delete '/comment_by_id', to: 'comments#destroy_by_id'
  put '/comments', to: 'comments#update'

  resources :subscriptions do
    member do
      get :unsubscribe, to: 'subscriptions#destroy'
    end
  end

  root to: 'application#welcome'

  namespace :admin do
    get 'dashboard', to: 'dashboard#show'
  end

  get '/help', to: 'application#help'

  get 'statistics/', to: 'statistics#show'
  get 'statistics/graphs', to: 'statistics#graphs'
  get 'statistics/graphs/user-activity', to: 'statistics#user_activity'
  get 'statistics/graphs/user-activity-history', to: 'statistics#user_activity_history'
  get 'statistics/graphs/rfc-activity', to: 'statistics#rfc_activity'
  get 'statistics/graphs/rfc-activity-history', to: 'statistics#rfc_activity_history'

  concern :statistics do
    member do
      get :statistics
    end
  end


  resources :consumers

  resources :execution_environments do
    member do
      get :shell
      post 'shell', as: :execute_command, action: :execute_command
      get :statistics
    end

    resources :errors, only: [:create, :index, :show]
    resources :hints
  end

  post '/import_proforma_xml' => 'exercises#import_proforma_xml'

  resources :exercises do
    collection do
      match '', to: 'exercises#batch_update', via: [:patch, :put]
    end

    member do
      post :clone
      get :implement
      get :working_times
      post :intervention
      post :search
      get :statistics
      get :feedback
      get :reload
      post :submit
    end
  end

  resources :exercise_collections do
    member do
      get :statistics
    end
  end

  resources :proxy_exercises do
    member do
      post :clone
      get :reload
      post :submit
    end
  end

  resources :tags do
    member do
      post :clone
      get :reload
      post :submit
    end
  end

  resources :user_exercise_feedbacks do
    member do
      get :reload
      post :submit
    end
  end

  resources :interventions do
    member do
      post :clone
      get :reload
      post :submit
    end
  end

  resources :external_users, only: [:index, :show], concerns: :statistics do
    resources :exercises, concerns: :statistics
    member do
      get :tag_statistics
    end
  end

  namespace :code_ocean do
    resources :files, only: [:create, :destroy]
  end

  resources :file_types

  resources :internal_users do
    member do
      match 'activate', to: 'internal_users#activate', via: [:get, :patch, :put]
      match 'reset_password', to: 'internal_users#reset_password', via: [:get, :patch, :put]
    end
  end

  match '/forgot_password', as: 'forgot_password', to: 'internal_users#forgot_password', via: [:get, :post]

  resources :sessions, only: [:create, :destroy, :new]

  post '/lti/launch', as: 'lti_launch', to: 'sessions#create_through_lti'
  get '/lti/return', as: 'lti_return', to: 'sessions#destroy_through_lti'
  get '/sign_in', as: 'sign_in', to: 'sessions#new'
  delete '/sign_out', as: 'sign_out', to: 'sessions#destroy'

  resources :submissions, only: [:create, :index, :show] do
    member do
      get 'download', as: :download, action: :download
      get 'download/:filename', as: :download_file, constraints: {filename: FILENAME_REGEXP}, action: :download_file
      get 'render/:filename', as: :render, constraints: {filename: FILENAME_REGEXP}, action: :render_file
      get 'run/:filename', as: :run, constraints: {filename: FILENAME_REGEXP}, action: :run
      get :score
      get :statistics
      post :stop
      get 'test/:filename', as: :test, constraints: {filename: FILENAME_REGEXP}, action: :test
    end
  end

  resources :events, only: [:create]

  post "/evaluate", to: 'remote_evaluation#evaluate', via: [:post]

end

app/controllers/proxy_exercises_controller.rb
class ProxyExercisesController < ApplicationController
  include CommonBehavior

  before_action :set_exercise, only: MEMBER_ACTIONS + [:clone, :reload]

  def authorize!
    authorize(@proxy_exercise || @proxy_exercises)
  end
  private :authorize!

  def clone
    proxy_exercise = @proxy_exercise.duplicate(token: nil, exercises: @proxy_exercise.exercises)
    proxy_exercise.send(:generate_token)
    if proxy_exercise.save
      redirect_to(proxy_exercise, notice: t('shared.object_cloned', model:  ProxyExercise.model_name.human))
    else
      flash[:danger] = t('shared.message_failure')
      redirect_to(@proxy_exercise)
    end
  end

  def create
    myparams = proxy_exercise_params
    myparams[:exercises] = Exercise.find(myparams[:exercise_ids].reject { |c| c.empty? })
    @proxy_exercise = ProxyExercise.new(myparams)
    authorize!

    create_and_respond(object: @proxy_exercise)
  end

  def destroy
    destroy_and_respond(object: @proxy_exercise)
  end

  def edit
    @search = policy_scope(Exercise).search(params[:q])
    @exercises = @search.result.order(:title)
    authorize!
  end

  def proxy_exercise_params
    params[:proxy_exercise].permit(:description, :title, :exercise_ids  => [])
  end
  private :proxy_exercise_params

  def index
    @search = policy_scope(ProxyExercise).search(params[:q])
    @proxy_exercises = @search.result.order(:title).paginate(page: params[:page])
    authorize!
  end

  def new
    @proxy_exercise =  ProxyExercise.new
    @search = policy_scope(Exercise).search(params[:q])
    @exercises = @search.result.order(:title)
    authorize!
  end

  def set_exercise
    @proxy_exercise = ProxyExercise.find(params[:id])
    authorize!
  end
  private :set_exercise

  def show
    @search = @proxy_exercise.exercises.search
    @exercises = @proxy_exercise.exercises.search.result.order(:title) #@search.result.order(:title)
  end

  #we might want to think about auth here
  def reload
  end

  def update
    myparams = proxy_exercise_params
    myparams[:exercises] = Exercise.find(myparams[:exercise_ids].reject { |c| c.blank? })
    update_and_respond(object: @proxy_exercise, params: myparams)
  end

end

app/views/proxy_exercises/_form.html.slim
= form_for(@proxy_exercise, multipart: true) do |f|
  = render('shared/form_errors', object: @proxy_exercise)
  .form-group
    = f.label(:title)
    = f.text_field(:title, class: 'form-control', required: true)
  .form-group
    = f.label(:description)
    = f.pagedown_editor :description

  h3 Exercises
  .table-responsive
    table.table
      thead
        tr
          th = t('activerecord.attributes.exercise.selection')
          th = sort_link(@search, :title, t('activerecord.attributes.submission.exercise'))
          th = sort_link(@search, :created_at, t('shared.created_at'))
      = collection_check_boxes :proxy_exercise, :exercise_ids, @exercises, :id, :title do |b|
        tr
          td = b.check_box
          td = link_to(b.object, b.object)
          td = l(b.object.created_at, format: :short)

  .actions = render('shared/submit_button', f: f, object: @proxy_exercise)

app/views/proxy_exercises/edit.html.slim
h1 = t('activerecord.models.proxy_exercise.one', model: ProxyExercise.model_name.human)+ ": " + @proxy_exercise.title

= render('form')

app/views/proxy_exercises/index.html.slim
h1 = ProxyExercise.model_name.human(count: 2)

= render(layout: 'shared/form_filters') do |f|
  .form-group
    = f.label(:title_cont, t('activerecord.attributes.proxy_exercise.title'), class: 'sr-only')
    = f.search_field(:title_cont, class: 'form-control', placeholder: t('activerecord.attributes.proxy_exercise.title'))

.table-responsive
  table.table
    thead
      tr
        th = sort_link(@search, :title, t('activerecord.attributes.proxy_exercise.title'))
        th = t('activerecord.attributes.exercise.token')
        th = t('activerecord.attributes.proxy_exercise.files_count')
        th colspan=6 = t('shared.actions')
    tbody
      - @proxy_exercises.each do |proxy_exercise|
        tr data-id=proxy_exercise.id
          td = link_to(proxy_exercise.title,proxy_exercise)
          td = proxy_exercise.token
          td = proxy_exercise.count_files
          td = link_to(t('shared.edit'), edit_proxy_exercise_path(proxy_exercise)) if policy(proxy_exercise).edit?

          td
            .btn-group
              button.btn.btn-primary-outline.btn-xs.dropdown-toggle data-toggle="dropdown" type="button" = t('shared.actions_button')
              span.caret
              span.sr-only Toggle Dropdown
              ul.dropdown-menu.pull-right role="menu"
                li = link_to(t('shared.show'), proxy_exercise) if policy(proxy_exercise).show?
                li = link_to(t('shared.destroy'), proxy_exercise, data: {confirm: t('shared.confirm_destroy')}, method: :delete) if policy(proxy_exercise).destroy?
                li = link_to(t('.clone'), clone_proxy_exercise_path(proxy_exercise), data: {confirm: t('shared.confirm_destroy')}, method: :post) if policy(proxy_exercise).clone?

= render('shared/pagination', collection: @proxy_exercises)
p = render('shared/new_button', model: ProxyExercise)

app/views/proxy_exercises/new.html.slim
h1 = t('shared.new_model', model: ProxyExercise.model_name.human)

= render('form')

app/views/proxy_exercises/show.html.slim
- content_for :head do
  = javascript_include_tag('http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js')
  = stylesheet_link_tag('http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/default.min.css')

h1
  = @proxy_exercise.title
  - if policy(@proxy_exercise).edit?
    = render('shared/edit_button', object: @proxy_exercise)

= row(label: 'exercise.title', value: @proxy_exercise.title)
= row(label: 'proxy_exercise.files_count', value: @exercises.count)
= row(label: 'exercise.description', value: @proxy_exercise.description)
= row(label: 'exercise.token', value: @proxy_exercise.token)
h3 Exercises
.table-responsive
  table.table
    thead
      tr
        th = sort_link(@search, :title, t('activerecord.attributes.submission.exercise'))
        th = sort_link(@search, :created_at, t('shared.created_at'))
    - @proxy_exercise.exercises.each do |exercise|
      tr
        td = link_to(exercise.title, exercise)
        td = l(exercise.created_at, format: :short)