config/routes.rb
FILENAME_REGEXP = /[\w\.]+/ unless Kernel.const_defined?(:FILENAME_REGEXP)

Rails.application.routes.draw do
  resources :error_template_attributes
  resources :error_templates do
    member do
      put 'attribute', to: 'error_templates#add_attribute'
      delete 'attribute', to: 'error_templates#remove_attribute'
    end
  end
  resources :file_templates do
    collection do
      get 'by_file_type/:file_type_id', as: :by_file_type, action: :by_file_type
    end
  end
  resources :code_harbor_links
  resources :request_for_comments do
    member do
      get :mark_as_solved
      post :create_comment_exercise
      post :set_thank_you_note
    end
  end
  resources :comments
  get '/my_request_for_comments', as: 'my_request_for_comments', to: 'request_for_comments#get_my_comment_requests'
  get '/my_rfc_activity', as: 'my_rfc_activity', to: 'request_for_comments#get_rfcs_with_my_comments'

  delete '/comment_by_id', to: 'comments#destroy_by_id'
  put '/comments', to: 'comments#update'

  resources :subscriptions do
    member do
      get :unsubscribe, to: 'subscriptions#destroy'
    end
  end

  root to: 'application#welcome'

  namespace :admin do
    get 'dashboard', to: 'dashboard#show'
  end

  get '/help', to: 'application#help'

  get 'statistics/', to: 'statistics#show'
  get 'statistics/graphs', to: 'statistics#graphs'
  get 'statistics/graphs/user-activity', to: 'statistics#user_activity'
  get 'statistics/graphs/user-activity-history', to: 'statistics#user_activity_history'
  get 'statistics/graphs/rfc-activity', to: 'statistics#rfc_activity'
  get 'statistics/graphs/rfc-activity-history', to: 'statistics#rfc_activity_history'

  concern :statistics do
    member do
      get :statistics
    end
  end


  resources :consumers

  resources :execution_environments do
    member do
      get :shell
      post 'shell', as: :execute_command, action: :execute_command
      get :statistics
    end

    resources :errors, only: [:create, :index, :show]
    resources :hints
  end

  post '/import_proforma_xml' => 'exercises#import_proforma_xml'

  resources :exercises do
    collection do
      match '', to: 'exercises#batch_update', via: [:patch, :put]
    end

    member do
      post :clone
      get :implement
      get :working_times
      post :intervention
      post :search
      get :statistics
      get :feedback
      get :reload
      post :submit
    end
  end

  resources :exercise_collections do
    member do
      get :statistics
    end
  end

  resources :proxy_exercises do
    member do
      post :clone
      get :reload
      post :submit
    end
  end

  resources :tags do
    member do
      post :clone
      get :reload
      post :submit
    end
  end

  resources :user_exercise_feedbacks do
    member do
      get :reload
      post :submit
    end
  end

  resources :interventions do
    member do
      post :clone
      get :reload
      post :submit
    end
  end

  resources :external_users, only: [:index, :show], concerns: :statistics do
    resources :exercises, concerns: :statistics
    member do
      get :tag_statistics
    end
  end

  namespace :code_ocean do
    resources :files, only: [:create, :destroy]
  end

  resources :file_types

  resources :internal_users do
    member do
      match 'activate', to: 'internal_users#activate', via: [:get, :patch, :put]
      match 'reset_password', to: 'internal_users#reset_password', via: [:get, :patch, :put]
    end
  end

  match '/forgot_password', as: 'forgot_password', to: 'internal_users#forgot_password', via: [:get, :post]

  resources :sessions, only: [:create, :destroy, :new]

  post '/lti/launch', as: 'lti_launch', to: 'sessions#create_through_lti'
  get '/lti/return', as: 'lti_return', to: 'sessions#destroy_through_lti'
  get '/sign_in', as: 'sign_in', to: 'sessions#new'
  delete '/sign_out', as: 'sign_out', to: 'sessions#destroy'

  resources :submissions, only: [:create, :index, :show] do
    member do
      get 'download', as: :download, action: :download
      get 'download/:filename', as: :download_file, constraints: {filename: FILENAME_REGEXP}, action: :download_file
      get 'render/:filename', as: :render, constraints: {filename: FILENAME_REGEXP}, action: :render_file
      get 'run/:filename', as: :run, constraints: {filename: FILENAME_REGEXP}, action: :run
      get :score
      get :statistics
      post :stop
      get 'test/:filename', as: :test, constraints: {filename: FILENAME_REGEXP}, action: :test
    end
  end

  resources :events, only: [:create]

  post "/evaluate", to: 'remote_evaluation#evaluate', via: [:post]

end

app/models/exercise.rb
require 'nokogiri'
require File.expand_path('../../../lib/active_model/validations/boolean_presence_validator', __FILE__)

class Exercise < ActiveRecord::Base
  include Context
  include Creation
  include DefaultValues

  after_initialize :generate_token
  after_initialize :set_default_values

  belongs_to :execution_environment
  has_many :submissions

  has_and_belongs_to_many :proxy_exercises
  has_many :user_proxy_exercise_exercises
  has_many :exercise_collection_items
  has_many :exercise_collections, through: :exercise_collection_items
  has_many :user_exercise_interventions
  has_many :interventions, through: :user_exercise_interventions
  has_many :exercise_tags
  has_many :tags, through: :exercise_tags
  accepts_nested_attributes_for :exercise_tags
  has_many :user_exercise_feedbacks

  has_many :external_users, source: :user, source_type: ExternalUser, through: :submissions
  has_many :internal_users, source: :user, source_type: InternalUser, through: :submissions
  alias_method :users, :external_users

  scope :with_submissions, -> { where('id IN (SELECT exercise_id FROM submissions)') }

  validate :valid_main_file?
  validates :description, presence: true
  validates :execution_environment_id, presence: true
  validates :public, boolean_presence: true
  validates :title, presence: true
  validates :token, presence: true, uniqueness: true

  @working_time_statistics = nil
  attr_reader :working_time_statistics

  MAX_EXERCISE_FEEDBACKS = 20


  def average_percentage
    if average_score and maximum_score != 0.0 and submissions.exists?(cause: 'submit')
      (average_score / maximum_score * 100).round
    else
      0
    end
  end

  def average_score
    if submissions.exists?(cause: 'submit')
      maximum_scores_query = submissions.select('MAX(score) AS maximum_score').group(:user_id).to_sql.sub('$1', id.to_s)
      self.class.connection.execute("SELECT AVG(maximum_score) AS average_score FROM (#{maximum_scores_query}) AS maximum_scores").first['average_score'].to_f
    else 0 end
  end

  def average_number_of_submissions
    user_count = internal_users.distinct.count + external_users.distinct.count
    return user_count == 0 ? 0 : submissions.count() / user_count.to_f()
  end

  def time_maximum_score(user)
    submissions.where(user: user).where("cause IN ('submit','assess')").where("score IS NOT NULL").order("score DESC, created_at ASC").first.created_at rescue Time.zone.at(0)
  end

  def user_working_time_query
    "
      SELECT user_id,
             user_type,
             SUM(working_time_new) AS working_time,
             MAX(score) AS score
      FROM
        (SELECT user_id,
                user_type,
                score,
                CASE WHEN working_time >= '0:05:00' THEN '0' ELSE working_time END AS working_time_new
         FROM
            (SELECT user_id,
                    user_type,
                    score,
                    id,
                    (created_at - lag(created_at) over (PARTITION BY user_id, exercise_id
                                                        ORDER BY created_at)) AS working_time
            FROM submissions
            WHERE exercise_id=#{id}) AS foo) AS bar
      GROUP BY user_id, user_type
    "
  end

  def get_quantiles(quantiles)
    quantiles_str = "[" + quantiles.join(",") + "]"
    result = self.class.connection.execute("""
            WITH working_time AS
      (
               SELECT   user_id,
                        id,
                        exercise_id,
                        Max(score)                                                                                  AS max_score,
                        (created_at - Lag(created_at) OVER (partition BY user_id, exercise_id ORDER BY created_at)) AS working_time
               FROM     submissions
               WHERE    exercise_id = #{id}
               AND      user_type = 'ExternalUser'
               GROUP BY user_id,
                        id,
                        exercise_id), max_points AS
      (
               SELECT   context_id  AS ex_id,
                        Sum(weight) AS max_points
               FROM     files
               WHERE    context_type = 'Exercise'
               AND      context_id = #{id}
               AND      role = 'teacher_defined_test'
               GROUP BY context_id),
      -- filter for rows containing max points
      time_max_score AS
      (
             SELECT *
             FROM   working_time W1,
                    max_points MS
             WHERE  w1.exercise_id = ex_id
             AND    w1.max_score = ms.max_points),
      -- find row containing the first time max points
      first_time_max_score AS
      (
             SELECT id,
                    user_id,
                    exercise_id,
                    max_score,
                    working_time,
                    rn
             FROM   (
                             SELECT   id,
                                      user_id,
                                      exercise_id,
                                      max_score,
                                      working_time,
                                      Row_number() OVER(partition BY user_id, exercise_id ORDER BY id ASC) AS rn
                             FROM     time_max_score) T
             WHERE  rn = 1), times_until_max_points AS
      (
             SELECT w.id,
                    w.user_id,
                    w.exercise_id,
                    w.max_score,
                    w.working_time,
                    m.id AS reachedmax_at
             FROM   working_time W,
                    first_time_max_score M
             WHERE  w.user_id = m.user_id
             AND    w.exercise_id = m.exercise_id
             AND    w.id <= m.id),
      -- if user never makes it to max points, take all times
      all_working_times_until_max AS (
      (
             SELECT id,
                    user_id,
                    exercise_id,
                    max_score,
                    working_time
             FROM   times_until_max_points)
      UNION ALL
                (
                       SELECT id,
                              user_id,
                              exercise_id,
                              max_score,
                              working_time
                       FROM   working_time W1
                       WHERE  NOT EXISTS
                              (
                                     SELECT 1
                                     FROM   first_time_max_score F
                                     WHERE  f.user_id = w1.user_id
                                     AND    f.exercise_id = w1.exercise_id))), filtered_times_until_max AS
      (
             SELECT user_id,
                    exercise_id,
                    max_score,
                    CASE
                           WHEN working_time >= '0:05:00' THEN '0'
                           ELSE working_time
                    END AS working_time_new
             FROM   all_working_times_until_max ), result AS
      (
               SELECT   e.external_id AS external_user_id,
                        f.user_id,
                        exercise_id,
                        Max(max_score)        AS max_score,
                        Sum(working_time_new) AS working_time
               FROM     filtered_times_until_max f,
                        external_users e
               WHERE    f.user_id = e.id
               GROUP BY e.external_id,
                        f.user_id,
                        exercise_id )
      SELECT   unnest(percentile_cont(array#{quantiles_str}) within GROUP (ORDER BY working_time))
      FROM     result
    """)
    if result.count > 0
      quantiles.each_with_index.map{|q,i| Time.parse(result[i]["unnest"]).seconds_since_midnight}
    else
      quantiles.map{|q| 0}
    end

  end

  def retrieve_working_time_statistics
    @working_time_statistics = {}
    self.class.connection.execute(user_working_time_query).each do |tuple|
      @working_time_statistics[tuple['user_id'].to_i] = tuple
    end
  end

  def average_working_time
    self.class.connection.execute("""
      SELECT avg(working_time) as average_time
      FROM
        (#{user_working_time_query}) AS baz;
    """).first['average_time']
  end

  def average_working_time_for(user_id)
    if @working_time_statistics == nil
      retrieve_working_time_statistics()
    end
    @working_time_statistics[user_id]["working_time"]
  end

  def accumulated_working_time_for_only(user)
    user_type = user.external_user? ? "ExternalUser" : "InternalUser"
    Time.parse(self.class.connection.execute("""
        WITH WORKING_TIME AS
        (SELECT user_id,
                           id,
                           exercise_id,
                           max(score) AS max_score,
                           (created_at - lag(created_at) OVER (PARTITION BY user_id, exercise_id
                                                               ORDER BY created_at)) AS working_time
                   FROM submissions
                   WHERE exercise_id = #{id} AND user_id = #{user.id} AND user_type = '#{user_type}'
                   GROUP BY user_id, id, exercise_id),
        MAX_POINTS AS
        (SELECT context_id AS ex_id, sum(weight) AS max_points FROM files WHERE context_type = 'Exercise' AND context_id = #{id} AND role = 'teacher_defined_test' GROUP BY context_id),

        -- filter for rows containing max points
        TIME_MAX_SCORE AS
        (SELECT *
        FROM WORKING_TIME W1, MAX_POINTS MS
        WHERE W1.exercise_id = ex_id AND W1.max_score = MS.max_points),

        -- find row containing the first time max points
        FIRST_TIME_MAX_SCORE AS
        ( SELECT id,USER_id,exercise_id,max_score,working_time, rn
          FROM (
            SELECT id,USER_id,exercise_id,max_score,working_time,
                ROW_NUMBER() OVER(PARTITION BY user_id, exercise_id ORDER BY id ASC) AS rn

app/views/exercises/_code_field.html.slim
.form-group class="form-group-#{attribute.to_s.gsub('_', '-')}"
  = form.label(attribute, label)
  | &nbsp;
  a.toggle-input data={text_initial: t('shared.upload_file'), text_toggled: t('shared.back')} href='#' = t('shared.upload_file')
  = form.text_area(attribute, class: 'code-field form-control', rows: 16, style: "display:none;")
  = form.file_field(attribute, class: 'alternative-input form-control', disabled: true)
  = render partial: 'editor_edit', locals: { exercise: @exercise }

app/views/exercises/_editor_edit.html.slim
#editor-edit.panel-group.row.original-input data-exercise-id=@exercise.id
  #frames
    .edit-frame
      .editor-content.hidden
      .editor

app/views/exercises/_editor_file_tree.html.slim
div id='sidebar-collapsed' class=(@exercise.hide_file_tree ? '' : 'hidden')
  = render('editor_button', classes: 'btn-block btn-primary btn-sm', data: {:'data-toggle' => 'tooltip', :'data-placement' => 'right'}, icon: 'fa fa-plus-square', id: 'sidebar-collapse-collapsed', label:'', title:t('exercises.editor.expand_action_sidebar'))

  - if @exercise.allow_file_creation and not @exercise.hide_file_tree?
    = render('editor_button', classes: 'btn-block btn-primary btn-sm enforce-top-margin', data: {:'data-cause' => 'file', :'data-toggle' => 'tooltip', :'data-placement' => 'right'}, icon: 'fa fa-plus', id: 'create-file-collapsed', label:'', title: t('exercises.editor.create_file'))

  = render('editor_button', classes: 'btn-block btn-primary btn-sm enforce-top-margin', data: {:'data-toggle' => 'tooltip', :'data-placement' => 'right'}, icon: 'fa fa-download', id: 'download-collapsed', label:'', title: t('exercises.editor.download'))
  = render('editor_button', classes: 'btn-block btn-primary btn-sm enforce-top-margin', data: {:'data-message-confirm' => t('exercises.editor.confirm_start_over'), :'data-url' => reload_exercise_path(@exercise), :'data-toggle' => 'tooltip', :'data-placement' => 'right'}, icon: 'fa fa-history', id: 'start-over-collapsed', label:'', title: t('exercises.editor.start_over'))
  - if !@course_token.blank?
    = render('editor_button', classes: 'btn-block btn-primary btn-sm enforce-top-margin', data: {:'data-toggle' => 'tooltip', :'data-placement' => 'right'}, icon: 'fa fa-search', id: 'sidebar-search-collapsed', label: '', title: t('search.search_in_forum'))

div id='sidebar-uncollapsed' class=(@exercise.hide_file_tree ? 'hidden' : '')
  = render('editor_button', classes: 'btn-block btn-primary btn-sm', icon: 'fa fa-minus-square', id: 'sidebar-collapse', label: t('exercises.editor.collapse_action_sidebar'))

  div class=(@exercise.hide_file_tree ? 'hidden' : '')
    hr

    #files data-entries=FileTree.new(files).to_js_tree

    hr

  - if @exercise.allow_file_creation and not @exercise.hide_file_tree?
    = render('editor_button', classes: 'btn-block btn-primary btn-sm', data: {:'data-cause' => 'file'}, icon: 'fa fa-plus', id: 'create-file', label: t('exercises.editor.create_file'))
    = render('editor_button', classes: 'btn-block btn-warning btn-sm', data: {:'data-cause' => 'file', :'data-message-confirm' => t('shared.confirm_destroy')}, icon: 'fa fa-times', id: 'destroy-file', label: t('exercises.editor.destroy_file'))

  = render('editor_button', classes: 'btn-block btn-primary btn-sm enforce-top-margin', icon: 'fa fa-download', id: 'download', label: t('exercises.editor.download'))
  = render('editor_button', classes: 'btn-block btn-primary btn-sm', data: {:'data-message-confirm' => t('exercises.editor.confirm_start_over'), :'data-url' => reload_exercise_path(@exercise)}, icon: 'fa fa-history', id: 'start-over', label: t('exercises.editor.start_over'))

  //- if !@course_token.blank?
      .input-group.enforce-top-margin
        .enforce-right-margin
          = text_field_tag 'search-input-text', nil, placeholder: t('search.search_in_forum'), class: 'form-control'
        .input-group-btn
          = button_tag(class: 'btn btn-primary', id: 'btn-search-col') do
            i.fa.fa-search

- if @exercise.allow_file_creation?
  = render('shared/modal', id: 'modal-file', template: 'code_ocean/files/_form', title: t('exercises.editor.create_file'))

app/views/exercises/_editor_output.html.slim
div id='output_sidebar_collapsed'
  = render('editor_button', classes: 'btn-block btn-primary btn-sm', data: {:'data-toggle' => 'tooltip', :'data-placement' => 'left'}, title: t('exercises.editor.expand_output_sidebar'), icon: 'fa fa-plus-square', id: 'toggle-sidebar-output-collapsed', label: '')
div id='output_sidebar_uncollapsed' class='hidden col-sm-12 enforce-bottom-margin' data-message-no-output=t('exercises.implement.no_output')
  .row
    = render('editor_button', classes: 'btn-block btn-primary btn-sm', icon: 'fa fa-minus-square', id: 'toggle-sidebar-output', label: t('exercises.editor.collapse_output_sidebar'))

  div.enforce-big-top-margin.hidden id='score_div'
    #results
      h2 = t('exercises.implement.results')
      p.test-count == t('exercises.implement.test_count', count: 0)
      ul.list-unstyled
      ul#dummies.hidden.list-unstyled
        li.panel.panel-default
          .panel-heading
            h3.panel-title == t('exercises.implement.file', filename: '', number: 0)
          .panel-body
            = row(label: 'exercises.implement.passed_tests', value: t('shared.out_of', maximum_value: 0, value: 0).html_safe)
            = row(label: 'activerecord.attributes.submission.score', value: t('shared.out_of', maximum_value: 0, value: 0).html_safe)
            = row(label: 'exercises.implement.feedback')
            = row(label: 'exercises.implement.error_messages')
            /= row(label: 'exercises.implement.output', value: link_to(t('shared.show'), '#'))
    #score data-maximum-score=@exercise.maximum_score data-score=@submission.try(:score)
      h4
        span == "#{t('activerecord.attributes.submission.score')}:&nbsp;"
        span.score
      .progress
        .progress-bar role='progressbar'

    br
    - if lti_outcome_service?(@exercise.id, external_user_id, consumer_id)
      p.text-center = render('editor_button', classes: 'btn-lg btn-success', data: {:'data-url' => submit_exercise_path(@exercise)}, icon: 'fa fa-send', id: 'submit', label: t('exercises.editor.submit'))
    - else
      p.text-center = render('editor_button', classes: 'btn-lg btn-warning-outline', data: {:'data-placement' => 'bottom', :'data-tooltip' => true}, icon: 'fa fa-clock-o', id: 'submit_outdated', label: t('exercises.editor.exercise_deadline_passed'), title: t('exercises.editor.tooltips.exercise_deadline_passed'))
    hr

  div.enforce-big-top-margin
    #turtlediv
      canvas#turtlecanvas.hidden width=400 height=400
  div.enforce-big-top-margin
    #hint
      .panel.panel-warning
        .panel-heading = t('exercises.implement.hint')
        .panel-body
  div.enforce-big-top-margin
    #prompt.input-group.hidden
      span.input-group-addon data-prompt=t('exercises.editor.input') = t('exercises.editor.input')
      input#prompt-input.form-control type='text'
      span.input-group-btn
        button#prompt-submit.btn.btn-primary type="button" = t('exercises.editor.send')
    #error-hints
      .heading = t('exercises.implement.error_hints.heading')
      ul.body
    #output
      pre = t('exercises.implement.no_output_yet')
    - if CodeOcean::Config.new(:code_ocean).read[:flowr][:enabled]
      #flowrHint.panel.panel-info data-url=CodeOcean::Config.new(:code_ocean).read[:flowr][:url] role='tab'
        .panel-heading = 'Gain more insights here'
        .panel-body

app/views/exercises/_form.html.slim
- execution_environments = ExecutionEnvironment.where('file_type_id IS NOT NULL').select(:file_type_id, :id)
- file_types = FileType.where('file_extension IS NOT NULL').select(:file_extension, :id)

= form_for(@exercise, data: {execution_environments: execution_environments, file_types: file_types}, multipart: true) do |f|
  = render('shared/form_errors', object: @exercise)
  .form-group
    = f.label(:title)
    = f.text_field(:title, class: 'form-control', required: true)
  .form-group
    = f.label(:description)
    = f.pagedown_editor :description
  .form-group
    = f.label(:execution_environment_id)
    = f.collection_select(:execution_environment_id, @execution_environments, :id, :name, {}, class: 'form-control')
  /.form-group
    = f.label(:instructions)
    = f.hidden_field(:instructions)
    .form-control.markdown
  .checkbox
    label
      = f.check_box(:public)
      = t('activerecord.attributes.exercise.public')
  .checkbox
    label
      = f.check_box(:hide_file_tree)
      = t('activerecord.attributes.exercise.hide_file_tree')
  .checkbox
    label
      = f.check_box(:allow_file_creation)
      = t('activerecord.attributes.exercise.allow_file_creation')
  .checkbox
    label
      = f.check_box(:allow_auto_completion)
      = t('activerecord.attributes.exercise.allow_auto_completion')
  .form-group
    = f.label(t('activerecord.attributes.exercise.difficulty'))
    = f.number_field :expected_difficulty, in: 1..10, step: 1

  h2 = t('exercises.form.tags')
  ul.list-unstyled.panel-group
    li.panel.panel-default
      .panel-heading role="tab" id="heading"
        a.file-heading data-toggle="collapse" href="#tag-collapse"
          div.clearfix role="button"
            span = t('exercises.form.click_to_collapse')
      .panel-collapse.collapse id="tag-collapse" role="tabpanel"
        .table-responsive
          table.table#tags-table
            thead
              tr
                th = t('activerecord.attributes.exercise.selection')
                th = sort_link(@search, :title, t('activerecord.attributes.tag.name'))
                th = t('activerecord.attributes.tag.difficulty')
              = collection_check_boxes :exercise, :tag_ids, @exercise_tags, :tag_id, :id do |b|
                tr
                  td = b.check_box
                  td = b.object.tag.name
                  td = number_field "tag_factors[#{b.object.tag.id}]", :factor, :value => b.object.factor, in: 1..10, step: 1

  h2 = t('activerecord.attributes.exercise.files')
  ul#files.list-unstyled.panel-group
    = f.fields_for :files do |files_form|
      = render('file_form', f: files_form)

  a#add-file.btn.btn-default.btn-sm.pull-right href='#' = t('.add_file')
  ul#dummies.hidden = f.fields_for(:files, CodeOcean::File.new, child_index: 'index') do |files_form|
    = render('file_form', f: files_form)

  .actions = render('shared/submit_button', f: f, object: @exercise)

app/views/exercises/feedback.html.slim
h1 = link_to(@exercise, exercise_path(@exercise))

.feedback-page
  .header = t('activerecord.attributes.exercise.description')
  .value = render_markdown(@exercise.description)

  .header = t('activerecord.models.user_exercise_feedback.other')
  - if @feedbacks.nil? or @feedbacks.size == 0
    .no-feedback = t('user_exercise_feedback.no_feedback')

  ul.list-unstyled.panel-group
    - @feedbacks.each do |feedback|
      li.panel.panel-default
        .panel-heading role="tab" id="heading"
          div.clearfix.feedback-header
            span.username = link_to(feedback.user.name, statistics_external_user_exercise_path(id: @exercise.id, external_user_id: feedback.user.id))
            - if feedback.anomaly_notification
              i class="fa fa-envelope-o" data-placement="top" data-toggle="tooltip" data-container="body" title=feedback.anomaly_notification.reason
            span.date = feedback.created_at
        .panel-collapse role="tabpanel"
          .panel-body.feedback
            .text = feedback.feedback_text
            .difficulty = "#{t('user_exercise_feedback.difficulty')} #{feedback.difficulty}" if feedback.difficulty
            .worktime = "#{t('user_exercise_feedback.working_time')} #{feedback.user_estimated_worktime}" if feedback.user_estimated_worktime

  = render('shared/pagination', collection: @feedbacks)

  script type="text/javascript" $(function () { $('[data-toggle="tooltip"]').tooltip() });

app/views/exercises/index.html.slim
h1 = Exercise.model_name.human(count: 2)

= render(layout: 'shared/form_filters') do |f|
  .form-group
    = f.label(:execution_environment_id_eq, t('activerecord.attributes.exercise.execution_environment'), class: 'sr-only')
    = f.collection_select(:execution_environment_id_eq, ExecutionEnvironment.with_exercises, :id, :name, class: 'form-control', prompt: t('activerecord.attributes.exercise.execution_environment'))
  .form-group
    = f.label(:title_cont, t('activerecord.attributes.exercise.title'), class: 'sr-only')
    = f.search_field(:title_cont, class: 'form-control', placeholder: t('activerecord.attributes.exercise.title'))

.table-responsive
  table.table
    thead
      tr
        th = sort_link(@search, :title, t('activerecord.attributes.exercise.title'))
        th = sort_link(@search, :execution_environment_id, t('activerecord.attributes.exercise.execution_environment'))
        th = t('.test_files')
        th = t('activerecord.attributes.exercise.maximum_score')
        th = t('activerecord.attributes.exercise.tags')
        th = t('activerecord.attributes.exercise.difficulty')
        th
          = t('activerecord.attributes.exercise.public')
          - if policy(Exercise).batch_update?
            br
            span.batch = link_to(t('shared.batch_update'), '#', 'data-text' => t('shared.update', model: t('activerecord.models.exercise.other')))
        th colspan=6 = t('shared.actions')
    tbody
      - @exercises.each do |exercise|
        tr data-id=exercise.id
          td = exercise.title
          td = link_to_if(exercise.execution_environment && policy(exercise.execution_environment).show?, exercise.execution_environment, exercise.execution_environment)
          td = exercise.files.teacher_defined_tests.count
          td = exercise.maximum_score
          td = exercise.exercise_tags.count
          td = exercise.expected_difficulty
          td.public data-value=exercise.public? = symbol_for(exercise.public?)
          td = link_to(t('shared.edit'), edit_exercise_path(exercise)) if policy(exercise).edit?
          td = link_to(t('.implement'), implement_exercise_path(exercise)) if policy(exercise).implement?
          td = link_to(t('shared.statistics'), statistics_exercise_path(exercise)) if policy(exercise).statistics?

          td
            .btn-group
              button.btn.btn-primary-outline.btn-xs.dropdown-toggle data-toggle="dropdown" type="button" = t('shared.actions_button')
              span.caret
              span.sr-only Toggle Dropdown
              ul.dropdown-menu.pull-right role="menu"
                li = link_to(t('shared.show'), exercise) if policy(exercise).show?
                li = link_to(t('activerecord.models.user_exercise_feedback.other'), feedback_exercise_path(exercise)) if policy(exercise).feedback?
                li = link_to(t('shared.destroy'), exercise, data: {confirm: t('shared.confirm_destroy')}, method: :delete) if policy(exercise).destroy?
                li = link_to(t('.clone'), clone_exercise_path(exercise), data: {confirm: t('shared.confirm_destroy')}, method: :post) if policy(exercise).clone?

= render('shared/pagination', collection: @exercises)
p = render('shared/new_button', model: Exercise)